# ****************************************************************************
# NOTES:
#
# Workflow for cache testing.
#
#
# ****************************************************************************

name: Data update

on:
  workflow_dispatch:

jobs:
  data-update:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with: 
        r-version: 4.1.3
  
    - name: Cache R packages
      id: cache
      uses: actions/cache@v4
      with:
        path: ${{ env.R_LIBS_USER }}
        key: ${{ runner.os }}-dataupdate
        restore-keys: |
          ${{ runner.os }}-

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        install.packages(c("dplyr", "cansim", "dotenv"))
      shell: Rscript {0}

    - name: Do stuff
      run: |
        source("tests/caching.R")
      shell: Rscript {0}

    - name: Save R cache
      id: cache-dataupdate-saves
      uses: actions/cache/save@v4
      with: 
        path: ${{ env.R_LIBS_USER }}
        key: ${{ steps.cache.outputs.cache-primary-key }}

